/*
  pageTemplateInputUiId: 300,
  dependencyTemplateInputUiId: 0,
  actionType: null,
  tableName: 'logistics_order',
  fieldName: 'transportType',
  fieldHeader: '运输类型',
  isExtjson: '0',
  posIndex: 2,
  posWidth: 1,
  isOptional: true,
  isSearch: false,
  validation: null,
  inputType: 'select',
  dictionaryType: 'String',
  reqUrl: null,
  reqParams: null,
  rspFields: '["铁路", "公路"]', */

import constant from '../../iloop-form/utils/constant';

const DATABASE_COLUMNS_TYPE_MAP = {
  bigint: 'integer',
  datetime: 'date',
  timestamp: 'date',
  varchar: 'text',
  char: 'checkbox',
  decimal: 'float',
  int: 'integer',
};

const GRID_ATTRIBUTES = [
  'fieldName',
  'fieldHeader',
  'isExtjson',
  'posWidth',
  'posIndex',
  'isHidden',
  'isSearch',
  'fieldLinkkeys',
];

const COMMON_ATTRIBUTES = [
  'inputType',
  'fieldName',
  'fieldHeader',
  'isExtjson',
  'posWidth',
  'posIndex',
  'isOptional',
  'isHidden',
  'isDisable',
  'isSearch',
  'placeholder',
];

const COMPONENTS_ATTRIBUTES = {
  text: ['maxLength', 'validation'],
  textarea: ['maxLength', 'validation'],
  date: ['showTime'],
  daterange: ['showTime'],
  time: ['showTime'],
  select: [
    'mode',
    'dictionaryType',
    'reqUrl',
    'rspFields',
    'reqParams',
    'list',
    'dependencyTemplateInputUiId',
  ],
  autocomplete: [
    'dictionaryType',
    'reqUrl',
    'reqParams',
    'rspFields',
    'list',
    'valueInOptions',
    'reloadOnChange',
    'dependencyTemplateInputUiId',
  ],
  integer: ['maxLength', 'validation'],
  float: ['toFix', 'maxLength', 'validation'],
  address: ['changeOnSelect', 'rspFields'],
  upload: [
    'type',
    'fileSize',
    'readonly',
    'template',
    'action',
    'accept',
    'multiple',
    'maxLength',
    'autoupload',
  ],
};

// const PLATEHOLDERS = {
//   text: '文本框',
//   textarea: '多行文本框',
//   date: '日期',
//   daterange: '时间范围',
//   time: '时间',
//   select: '下拉列表',
//   autocomplete: '自动选择',
//   integer: '整数',
//   float: '浮点数',
//   address: '地址',
//   upload: '附件上传',
// };

const PLATEHOLDERS = (constant.controlTypes || []).reduce((total, next) => {
  Object.assign(total, { [next.inputType]: next.fieldHeader });
  return total;
}, {});

const attributes = [
  // inputType
  /*
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'inputType',
    fieldHeader: '控件类型',
    isExtjson: '0',
    posIndex: 9,
    posWidth: 1,
    isOptional: true,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'text',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: constant.controlTypes.map(item => {
      return item.inputType;
    })
  },
  */
  // fieldName
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'fieldName',
    fieldHeader: '名称',
    isExtjson: '0',
    posIndex: 2,
    posWidth: 1,
    isOptional: true,
    isHidden: true,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'text',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // fieldHeader
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'fieldHeader',
    fieldHeader: '标题',
    isExtjson: '0',
    posIndex: 3,
    posWidth: 1,
    isOptional: true,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'text',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // posWidth
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'posWidth',
    fieldHeader: '占宽',
    isExtjson: '0',
    posIndex: 4,
    posWidth: 1,
    isOptional: false,
    isHidden: true,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'integer',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // isOptional
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'isOptional',
    fieldHeader: '必填',
    isExtjson: '0',
    posIndex: 5,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'checkbox',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // isHidden
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'isHidden',
    fieldHeader: '隐藏',
    isExtjson: '0',
    posIndex: 6,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'checkbox',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // isDisable
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'isDisable',
    fieldHeader: '禁用',
    isExtjson: '0',
    posIndex: 6,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'checkbox',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // isExtjson
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'isExtjson',
    fieldHeader: '扩展字段',
    isExtjson: '0',
    posIndex: 7,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: true,
    isSearch: false,
    validation: null,
    inputType: 'checkbox',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // validation
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'validation',
    fieldHeader: '校验',
    isExtjson: '0',
    posIndex: 8,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'select',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
    mode: 'multiple',
  },
  // placeholder
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'placeholder',
    fieldHeader: '占位符',
    isExtjson: false,
    posIndex: 10,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'text',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // maxLength
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'maxLength',
    fieldHeader: '最大长度',
    isExtjson: '0',
    posIndex: 10,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'integer',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // select
  // mode
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'mode',
    fieldHeader: '模式', //
    isExtjson: '0',
    posIndex: 11,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'select',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: '["multiple", "tags"]',
  },
  // dictionaryType
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'dictionaryType',
    fieldHeader: '数据字典',
    isExtjson: '0',
    posIndex: 12,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'select',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // valueInOptions
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'valueInOptions',
    fieldHeader: '下拉列表里取值',
    isExtjson: '0',
    posIndex: 18,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'checkbox',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // reloadOnChange
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'reloadOnChange',
    fieldHeader: '按需加载',
    isExtjson: '0',
    posIndex: 18,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'checkbox',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // dependencyTemplateInputUiId
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'dependencyTemplateInputUiId',
    fieldHeader: '依赖',
    isExtjson: '0',
    posIndex: 1,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'text',
    dictionaryType: 'String',
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // select, autocomplete
  // reqUrl
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'reqUrl',
    fieldHeader: '请求url',
    isExtjson: '0',
    posIndex: 13,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'text',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },

  // address
  // changeOnSelect
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'changeOnSelect',
    fieldHeader: '改变时选中',
    isExtjson: '0',
    posIndex: 18,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'checkbox',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // reqParams
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'reqParams',
    fieldHeader: '请求参数',
    isExtjson: '0',
    posIndex: 14,
    posWidth: 1,
    isOptional: false,
    isHidden: true,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'text',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // rspFields
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'rspFields',
    fieldHeader: '展示字段',
    isExtjson: '0',
    posIndex: 15,
    posWidth: 1,
    isOptional: false,
    isHidden: true,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'text',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // list
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'list',
    fieldHeader: '下拉列表',
    isExtjson: '0',
    posIndex: 15,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'text',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'fieldLinkkeys',
    fieldHeader: '链接配置',
    isExtjson: false,
    posIndex: 15,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'text',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // 数字 float
  // toFix
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'toFix',
    fieldHeader: '精度',
    isExtjson: '0',
    posIndex: 16,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'integer',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // 日期
  // showTime
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'showTime',
    fieldHeader: '显示时间',
    isExtjson: '0',
    posIndex: 17,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'checkbox',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // upload
  // type
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'type',
    fieldHeader: '附件类型',
    isExtjson: '0',
    posIndex: 19,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'select',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: '["picture", "file"]',
  },
  // fileSize
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'fileSize',
    fieldHeader: '文本大小',
    isExtjson: '0',
    posIndex: 20,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'integer',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // readonly
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'readonly',
    fieldHeader: '只读',
    isExtjson: '0',
    posIndex: 21,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'checkbox',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // template
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'template',
    fieldHeader: '模版',
    isExtjson: '0',
    posIndex: 22,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'text',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
  // handleUpload
  {
    pageTemplateInputUiId: 300,
    dependencyTemplateInputUiId: 0,
    actionType: null,
    tableName: 'template',
    fieldName: 'handleUpload',
    fieldHeader: '处理上传',
    isExtjson: '0',
    posIndex: 23,
    posWidth: 1,
    isOptional: false,
    isHidden: false,
    isDisable: false,
    isSearch: false,
    validation: null,
    inputType: 'text',
    dictionaryType: null,
    reqUrl: null,
    reqParams: null,
    rspFields: null,
  },
];

function getAttributes(type) {
  const attrs = [...COMMON_ATTRIBUTES, ...(COMPONENTS_ATTRIBUTES[type || 'default'] || [])];
  const resultAttr = (attributes || []).filter(it => {
    return attrs.includes(it.fieldName);
  });
  return resultAttr;
}

function getGridAttributes() {
  const resultAttr = (attributes || []).filter(it => {
    return GRID_ATTRIBUTES.includes(it.fieldName);
  });
  return resultAttr;
}

export default {
  GRID_ATTRIBUTES,
  COMMON_ATTRIBUTES,
  COMPONENTS_ATTRIBUTES,
  PLATEHOLDERS,
  DATABASE_COLUMNS_TYPE_MAP,
  attributes,
  getAttributes,
  getGridAttributes,
};
